### ISSUE TITLE
package for scalagen

### ISSUE THREAD

**Issue by DavidDudson** [scalameta/scalagen#11]
Currently the package is `org.scalameta.scalagen`

I would like to change this to `scala.meta.gen`

This allows for imports like

```scala
import scala.meta._
import scala.meta.contrib._
import scala.meta.gen._
```

**Comment by DavidDudson** [comment]
@xeno-by @olafurpg What are your thoughts?

**Comment by SethTisue** [comment]
`scala._` namespace should contain the Scala standard library and nothing else. (We went around on this very thoroughly in the context of SPP.)

**Comment by DavidDudson** [comment]
Then our options are:

- `org.scalameta.scalagen`
- `org.scalameta.gen`
- `scalameta.gen`

Depending on whether we exclusively follow maven conventions, or prefer the shorthand.

**Comment by olafurpg** [comment]
@SethTisue Can you elaborate what this means for existing libraries that are already using the `scala._` package like `scala.meta`?

**Comment by SethTisue** [comment]
> Can you elaborate what this means for existing libraries that are already using the scala._ package like scala.meta

well, the short answer is, they should stop, we don't do that anymore

but in practice, there is no policy document and no real governance around this. it's been a looooong time since anybody at Lightbend/Typesafe has tried to put something new in `scala._`, but there seems to be a stronger tradition of this at EPFL that has perhaps not entirely died out.

and there is certainly some de-facto grandfathering-in happening out there, e.g. scala-parser-combinators and the other modules that have split out of stdlib. (perhaps they will move to new packages at some point, as part of the overall SPP effort)

one possible middle ground is to wait until the next time you're breaking source compat and take that opportunity to change it, and perhaps provide a scalafix rewrite

a thread on https://contributors.scala-lang.org would be a better place to discuss further. I'd be happy to repeat any of this on such a thread. the main past thread on this subject that I can recall is https://contributors.scala-lang.org/t/should-the-scala-platform-modules-use-the-scala-namespace-or-a-common-namespace/422/25 (cc @jvican)

**Comment by SethTisue** [comment]
> no real governance around this

(P.S. well, my position — which I _think_ is the consensus, shared-understanding position currently — is that putting anything in `scala._` requires approval of the SIP committee. there is governance in that sense)

**Comment by xeno-by** [comment]
> well, the short answer is, they should stop, we don't do that anymore

@SethTisue I am not comfortable with the suggestion that we should consider retrospectively renaming `scala.meta`.

Scalameta is a vibrant project that has lots of production users and a successful ecosystem of tools built on top of it. Based on statistics provided by Sonatype, in November 2017 our main module has been downloaded more than 100k times. Also, there are numerous presentations and tutorials by about a dozen different authors - all mentioning `scala.meta`. This suggests that the proposed Scalafix rewrite only scratches the surface of the potential migration, and in reality this migration will be much more costly, if at all possible.

Moreover, as you said there are no official policies about package naming. At the time when Scalameta was founded, `scala.meta` was up for grabs and caused no controversy when we started using it. If the new naming rules were introduced just a couple weeks or even months after the inception of Scalameta, we could probably consider the renaming. However, by now it's been almost four years, and I think it's too late for that.

**Comment by SethTisue** [comment]
okay, I'm not the judge in this courtroom! sounds to me like you have a decent case to make for grandfathering

personally, I'm much more concerned that it (and other established projects) not be taken as a precedent for new projects, I'm not on the warpath about existing projects.

**Comment by olafurpg** [comment]
> personally, I'm much more concerned that the package name here (and on other established projects) not be taken as a precedent for new projects

I agree with the point of view that new projects should not reside under `scala._`. However, scalameta is not a new project: scalameta_2.11 and scalameta_2.12 combined had 125k downloads in November 2017. scalagen could easily have been a new module in the scalameta/scalameta repo but we decided to split into a separate repo under the same organization for easier maintainability.

I propose we stick with `scala.meta.gen` since that is consistent with the current holistic organization of scalameta modules.

**Comment by DavidDudson** [comment]
This has now been changed. Thank @SethTisue for your concerns and input. The public api is now under `scala.meta.gen` and the internals are under `org.scalameta.scalagen`
